apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: steamtrader
  name: steamtrader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steamtrader
  template:
    metadata:
      labels:
        app: steamtrader
    spec:
      containers:
      - name: steamtrader
        image: eisengrind/steamtrader:latest
        imagePullPolicy: Always
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: steamtrader-secret
              key: apikey
        - name: LOGIN
          valueFrom:
            secretKeyRef:
              name: steamtrader-secret
              key: login
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: steamtrader-secret
              key: password
        - name: SHAREDSECRET
          valueFrom:
            secretKeyRef:
              name: steamtrader-secret
              key: sharedsecret
        - name: PROCESSTIMEOUT
          value: "30"
        resources:
          limits:
            cpu: "0.1"
            memory: 0.06Gi
